server:
  port: 12011
spring:
  profiles: dev
cs:
  name: xiao-D
  password: dev123

---
server:
  port: 12022
spring:
  profiles: test
cs:
  name: xiao-T
  password: test123

---
server:
  port: 12033
spring:
  profiles: prod
cs:
  name: xiao-P
  password: prod123
